import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./Sidebar";
import Navbar from "./Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  console.log(children);
  console.log("children");

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="grid grid-cols-12 gap-6 my-16 lg:px-20 md:px-40 px-2">
          <div className="sidebar lg:col-span-3 col-span-12 back-white relative rounded-xl shadow-lg ">
            <Sidebar />
          </div>
          <div className=" lg:col-span-9 col-span-12 back-white relative rounded-xl overflow-hidden">
            <Navbar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
